import {chromium} from 'playwright';
import {preview} from 'vite';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {makeState,mockAPI,authenticate} from './state.mjs';
const server=await preview({preview:{host:'127.0.0.1',port:4181,strictPort:true}}),browser=await chromium.launch({...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{}),headless:true});
const results=[],errors=[],requests=[],state=makeState(),out='dist/HeroRui-preview';await mkdir(out,{recursive:true});
const context=await browser.newContext({locale:'zh-CN',viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']}),page=await context.newPage();await authenticate(page);await mockAPI(page,requests,state);page.on('pageerror',e=>errors.push(e.message));
const base='http://127.0.0.1:4181',go=async route=>{await page.goto(base+'/#/'+route);await page.reload();await page.locator('h1').waitFor()},wait=async fn=>{for(let i=0;i<60;i++){if(await fn())return;await page.waitForTimeout(100)}throw Error('Condition timed out')},last=e=>requests.filter(r=>r.endpoint===e).at(-1),shot=name=>page.screenshot({path:out+'/'+name+'.png',fullPage:true}),close=()=>page.locator('.ant-modal-close:visible, .ant-drawer-close:visible').click();
const test=async(name,fn)=>{try{await fn();results.push({name,status:'PASS'});console.log('PASS '+name)}catch(e){results.push({name,status:'FAIL',error:e.message});console.error('FAIL '+name+': '+e.message);await shot('failure-'+results.length);throw e}};
try{
await test('全新 React 首页与原 token 兼容',async()=>{await go('dashboard');await page.getByText('28.50',{exact:true}).waitFor();assert.equal(last('/user/info').headers.authorization,'preview-token');assert.equal(await page.locator('script[src*="umi.js"]').count(),0);await shot('dashboard')});
await test('公告详情',async()=>{await page.getByRole('button',{name:/欢迎来到/}).click();await page.getByRole('dialog').getByText('在这里管理订阅、查看用量，随时开始新的探索。').waitFor();await close()});
await test('订阅复制、二维码、协议及客户端链接',async()=>{await page.getByRole('button',{name:'一键订阅',exact:true}).click();await page.getByRole('button',{name:'复制订阅地址',exact:true}).click();assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/types=auto/);assert.equal(await page.locator('.client-grid a').count(),6);await page.getByRole('combobox',{name:'选择协议'}).click();await page.getByText('vless',{exact:true}).click();await page.keyboard.press('Escape');assert.match(await page.getByRole('textbox',{name:'订阅地址'}).inputValue(),/types=vless/);await page.getByRole('dialog').screenshot({path:out+'/subscription.png'});await close()});
await test('套餐列表及分类',async()=>{await go('plan');await page.locator('.plan-card').first().waitFor();assert.equal(await page.locator('.plan-card').count(),3);await shot('plan');await page.getByText('按流量',{exact:true}).click();assert.equal(await page.locator('.plan-card').count(),1)});
await test('周期选择、优惠券参数与金额',async()=>{await go('plan/1');await page.getByRole('button',{name:/季付/}).click();await page.getByPlaceholder('有优惠券？').fill('SCAR500');await page.getByRole('button',{name:'验证',exact:true}).click();await wait(()=>!!last('/user/coupon/check'));assert.equal(last('/user/coupon/check').body.period,'quarter_price');await page.locator('.summary-total').getByText('¥74.00',{exact:true}).waitFor();await shot('configure')});
await test('取消旧待支付订单并下单',async()=>{await page.getByRole('button',{name:'下单',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:/确\s*定/}).click();await wait(()=>!!last('/user/order/save'));assert.deepEqual(last('/user/order/save').body,{plan_id:'1',period:'quarter_price',coupon_code:'SCAR500'});assert.ok(requests.findIndex(r=>r.endpoint==='/user/order/cancel')<requests.findIndex(r=>r.endpoint==='/user/order/save'));await page.waitForURL('**/#/order/202609120001')});
await test('支付手续费与二维码结算',async()=>{await page.getByText('¥75.68',{exact:true}).waitFor();await shot('checkout');await page.getByRole('button',{name:'结账',exact:true}).click();await page.getByRole('dialog').getByText('请使用所选支付方式扫码付款').waitFor();assert.equal(last('/user/order/checkout').body.method,'1');await close()});
await test('付款轮询完成并更新订阅',async()=>{state.checkStatus=3;await page.getByText('订单已支付并开通。',{exact:true}).waitFor({timeout:10000});assert.equal(await page.getByRole('button',{name:'结账',exact:true}).count(),0);state.checkStatus=null});
await test('零元订单开通',async()=>{state.order={...state.order,status:0,total_amount:0};state.checkout={type:-1,data:true};await go('order/202609120001');await page.getByRole('button',{name:'结账',exact:true}).click();await page.getByText('订单已支付并开通。',{exact:true}).waitFor()});
await test('节点搜索及在线状态',async()=>{await go('node');await page.getByText('香港 · Hong Kong 01',{exact:true}).waitFor();await page.getByRole('textbox',{name:'搜索',exact:true}).fill('Tokyo');assert.equal(await page.locator('.node-grid .panel').count(),1)});
await test('计费流量倍率换算与原版一致',async()=>{await go('traffic');for(const name of ['1.00 GB','3.00 GB','8.00 GB'])await page.getByRole('cell',{name,exact:true}).waitFor()});
await test('知识库搜索、复制、跳转与内容安全',async()=>{await go('knowledge');await page.getByRole('textbox',{name:'搜索文档'}).fill('导入');await page.getByRole('button',{name:'搜索',exact:true}).click();await wait(()=>last('/user/knowledge/fetch')?.query.keyword==='导入');await page.getByRole('button',{name:/开始使用：导入订阅/}).click();await page.getByRole('button',{name:'复制示例'}).click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'https://example.invalid/s/preview');assert.equal(await page.evaluate(()=>window.__xss),undefined);await page.getByRole('button',{name:'下一篇'}).click();await wait(()=>last('/user/knowledge/fetch')?.query.id==='2');await close();await shot('knowledge')});
await test('创建工单与等级参数',async()=>{await go('ticket');await page.getByRole('button',{name:'新的工单',exact:true}).first().click();await page.getByRole('textbox',{name:'主题',exact:true}).fill('需要帮助');await page.getByRole('textbox',{name:'消息',exact:true}).fill('请协助检查连接');await page.getByRole('button',{name:'确认',exact:true}).click();await wait(()=>!!last('/user/ticket/save'));assert.equal(last('/user/ticket/save').body.level,'1')});
await test('工单会话回复与关闭',async()=>{await go('ticket/1');await page.getByRole('textbox',{name:'输入内容回复工单'}).fill('谢谢，已成功连接');await page.getByRole('button',{name:'回复',exact:true}).click();await page.getByText('谢谢，已成功连接',{exact:true}).waitFor();await shot('ticket-1');await page.getByRole('button',{name:/^关\s*闭$/}).click();await page.getByRole('dialog').getByRole('button',{name:/^关\s*闭$/}).click();await wait(()=>!!last('/user/ticket/close'));await page.locator('.closed-ticket').waitFor()});
await test('修改密码一致性验证与参数',async()=>{await go('profile');await page.getByRole('textbox',{name:'旧密码',exact:true}).fill('oldpassword');await page.getByRole('textbox',{name:'新密码',exact:true}).fill('newpassword');await page.getByRole('textbox',{name:'再次输入密码',exact:true}).fill('wrongvalue');await page.getByRole('button',{name:'保存',exact:true}).click();assert.equal(last('/user/changePassword'),undefined);await page.getByRole('textbox',{name:'再次输入密码',exact:true}).fill('newpassword');await page.getByRole('button',{name:'保存',exact:true}).click();await wait(()=>!!last('/user/changePassword'));assert.equal(last('/user/changePassword').body.new_password,'newpassword');await shot('profile')});
await test('订阅安全重置并刷新链接',async()=>{await page.getByRole('button',{name:'重置',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:/重\s*置/}).click();await wait(()=>!!last('/user/resetSecurity'));await go('dashboard');await page.getByRole('button',{name:'一键订阅',exact:true}).click();assert.match(await page.getByRole('textbox',{name:'订阅地址'}).inputValue(),/s\/reset/);await close()});
await test('通知开关与 Telegram 绑定',async()=>{await go('profile');await page.getByRole('tab',{name:'通知',exact:true}).click();await page.getByRole('switch',{name:'到期邮件提醒'}).click();await wait(()=>!!last('/user/update'));assert.equal(last('/user/update').body.remind_expire,'0');await page.getByRole('button',{name:'立即开始',exact:true}).click();await page.getByRole('dialog').getByText('@herorui_demo_bot').waitFor();await close()});
await test('邀请链接与生成邀请码',async()=>{await go('invite');await page.getByRole('button',{name:'复制链接',exact:true}).click();assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/#\/register\?code=SCAR2026$/);await page.getByRole('button',{name:'生成邀请码',exact:true}).click();await wait(()=>!!last('/user/invite/save'));await shot('invite')});
await test('佣金记录分页',async()=>{await page.getByTitle('2',{exact:true}).click();await wait(()=>last('/user/invite/details')?.query.current==='2');assert.equal(last('/user/invite/details').query.page_size,'10')});
await test('佣金划转以分提交',async()=>{await page.getByRole('button',{name:'划转',exact:true}).click();await page.getByRole('spinbutton',{name:'划转金额'}).fill('12.34');await page.getByRole('dialog').getByRole('button',{name:'确定',exact:true}).click();await wait(()=>!!last('/user/transfer'));assert.equal(last('/user/transfer').body.transfer_amount,'1234')});
await test('佣金提现表单',async()=>{await page.getByRole('button',{name:'推广佣金提现',exact:true}).click();await page.getByRole('combobox',{name:'提现方式'}).click();await page.locator('.ant-select-item-option-content').filter({hasText:'支付宝'}).click();await page.getByRole('textbox',{name:'提现账号'}).fill('alipay@example.com');await page.getByRole('dialog').getByRole('button',{name:'确定',exact:true}).click();await wait(()=>!!last('/user/ticket/withdraw'));assert.equal(last('/user/ticket/withdraw').body.withdraw_method,'支付宝');await page.waitForURL('**/#/ticket')});
// 语言下拉在页脚，antd 把选项渲染进 body 的浮层里并带展开动画。
// 直接 click 会撞上「选项不在视口内 / 元素不稳定」—— 先把触发器滚进视口，
// 再等浮层稳定下来，最后把选项本身也滚进视口再点。
const pickLanguage=async label=>{
 const trigger=page.getByRole('combobox',{name:'Language'});
 await trigger.scrollIntoViewIfNeeded();
 await trigger.click();
 const option=page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden) .ant-select-item-option').filter({hasText:label}).first();
 await option.waitFor({state:'visible'});
 // 用 DOM click 而不是 Playwright 的 click：浮层带展开动画，Playwright 的
 // 稳定性检查会一直判定「元素还在动」直到超时。事件本身是真实的 click，
 // rc-select 照常处理。
 await option.evaluate(el=>el.click());
};
await test('英语切换与请求语言',async()=>{await go('dashboard');await pickLanguage('English');await wait(()=>page.evaluate(()=>document.documentElement.lang==='en-US'));await go('node');assert.equal(last('/user/info').headers['content-language'],'en-US');await pickLanguage('简体中文')});
await test('深色模式持久化',async()=>{await page.getByRole('button',{name:'切换深色'}).click();await page.reload();await page.locator('html.dark').waitFor();await shot('dark');await page.getByRole('button',{name:'切换浅色'}).click()});
await test('手机导航与十个业务页面无横向溢出',async()=>{await page.setViewportSize({width:390,height:844});for(const route of ['dashboard','plan','plan/1','order','node','traffic','invite','profile','knowledge','ticket/1']){await go(route);await page.waitForTimeout(150);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Overflow: '+route)}await go('dashboard');await shot('mobile');await page.getByRole('button',{name:'打开导航'}).click();await page.locator('.drawer-nav').getByRole('link',{name:/流量明细/}).click();await page.waitForURL('**/#/traffic');await page.setViewportSize({width:1440,height:1000})});
await test('请求失败可重试',async()=>{state.fail['/user/server/fetch']={status:500,message:'网络暂不可用'};await go('node');await page.getByText('网络暂不可用').waitFor();delete state.fail['/user/server/fetch'];await page.getByRole('button',{name:/重\s*试/}).click();await page.getByText('香港 · Hong Kong 01',{exact:true}).waitFor()});
await test('空账户与空列表',async()=>{const before={transfer_enable:state.user.transfer_enable,u:state.user.u,d:state.user.d};state.empty=true;state.user.plan_id=null;state.user.transfer_enable=0;state.user.u=0;state.user.d=0;for(const route of ['dashboard','plan','node','knowledge','traffic','ticket'])await go(route);state.empty=false;state.user.plan_id=1;state.user.transfer_enable=before.transfer_enable;state.user.u=before.u;state.user.d=before.d});
await test('登录失效返回登录页',async()=>{state.fail['/user/info']={status:401,message:'登录已过期'};await page.goto(base+'/#/profile');await page.reload();await page.getByRole('button',{name:'登入',exact:true}).waitFor();assert.equal(await page.evaluate(()=>localStorage.getItem('VUE_NAIVE_ACCESS_TOKEN')),null);delete state.fail['/user/info']});
const auth=await browser.newPage({locale:'zh-CN',viewport:{width:1440,height:1000}}),authRequests=[],authState=makeState();await mockAPI(auth,authRequests,authState);auth.on('pageerror',e=>errors.push(e.message));
await test('登录邮箱白名单兼容',async()=>{authState.guest.email_whitelist_suffix=['example.com'];await auth.goto(base+'/#/login');await auth.getByRole('button',{name:'登入',exact:true}).waitFor();await auth.screenshot({path:out+'/login.png',fullPage:true});await auth.getByRole('textbox',{name:'邮箱',exact:true}).fill('hello@example.com');await auth.getByRole('textbox',{name:'密码',exact:true}).fill('password123');await auth.getByRole('button',{name:'登入',exact:true}).click();await auth.waitForURL('**/#/dashboard');assert.equal(authRequests.find(r=>r.endpoint==='/passport/auth/login').body.email,'hello@example.com')});
await test('注册验证码、条款及邀请码',async()=>{await auth.evaluate(()=>localStorage.clear());await auth.goto('about:blank');authState.guest={...authState.guest,is_email_verify:1,tos_url:'https://example.invalid/terms',is_invite_force:1};await auth.goto(base+'/#/register?code=INVITE123');await auth.reload();await auth.getByRole('textbox',{name:'邮箱',exact:true}).fill('newuser');await auth.getByRole('button',{name:'发送',exact:true}).click();await wait(()=>authRequests.some(r=>r.endpoint==='/passport/comm/sendEmailVerify'));assert.equal(authRequests.find(r=>r.endpoint==='/passport/comm/sendEmailVerify').body.email,'newuser@example.com');await auth.getByRole('textbox',{name:'邮箱验证码',exact:true}).fill('123456');await auth.getByRole('textbox',{name:'密码',exact:true}).fill('password123');await auth.getByRole('textbox',{name:'再次输入密码',exact:true}).fill('password123');await auth.getByRole('checkbox').check();await auth.getByRole('button',{name:'注册',exact:true}).click();await auth.waitForURL('**/#/dashboard');const req=authRequests.find(r=>r.endpoint==='/passport/auth/register');assert.equal(req.body.invite_code,'INVITE123');assert.equal(req.body.email,'newuser@example.com')});
await test('忘记密码重置',async()=>{await auth.evaluate(()=>localStorage.clear());await auth.goto('about:blank');await auth.goto(base+'/#/forgetpassword');await auth.reload();await auth.getByRole('textbox',{name:'邮箱',exact:true}).fill('hello');await auth.getByRole('textbox',{name:'邮箱验证码',exact:true}).fill('654321');await auth.getByRole('textbox',{name:'密码',exact:true}).fill('resetpass123');await auth.getByRole('textbox',{name:'再次输入密码',exact:true}).fill('resetpass123');await auth.getByRole('button',{name:'重置密码',exact:true}).click();await auth.waitForURL('**/#/login');assert.equal(authRequests.find(r=>r.endpoint==='/passport/auth/forget').body.email_code,'654321')});
await test('免密链接登录',async()=>{await auth.goto(base+'/#/login?verify=onetimetoken');await auth.reload();await auth.waitForURL('**/#/dashboard');assert.equal(authRequests.find(r=>r.endpoint==='/passport/auth/token2Login').query.verify,'onetimetoken')});
await test('生产包隔离与零浏览器异常',async()=>{const manifest=JSON.parse(await readFile('dist/HeroRui.manifest.json','utf8'));assert.ok(!Object.keys(manifest.files).some(f=>/umi|fixtures|tests/.test(f)));const blade=await readFile('theme/HeroRui/dashboard.blade.php','utf8');assert.match(blade,/@json\(\$heroruiSettings\)/);assert.match(blade,/\/theme\/\{\{\$theme\}\}\/assets/);assert.equal(errors.length,0,errors.join('\n'));assert.deepEqual(state.unexpected,[]);assert.deepEqual(authState.unexpected,[])});
}finally{await writeFile(out+'/test-results.json',JSON.stringify({results,errors,requests:requests.length},null,2));await browser.close();await new Promise(r=>server.httpServer.close(r));console.log(`${results.filter(r=>r.status==='PASS').length}/${results.length} checks passed`)}
