import React,{useState} from 'react';
import {Progress,Modal,Alert} from 'antd';
import {ArrowUpRight,BookOpen,MessageSquare,Plus,Wallet,Globe,Clock,Copy} from 'lucide-react';
import {Action,Panel,Status,Heading,useT,useAccount,useResource,Load,Rich,money,bytes,date,navigate,useAction,copyText} from './core';
import {Subscription} from './subscription';
import {CheckinTile} from './checkin';
import {TelegramChannel} from './clients';
export function Dashboard(){
 const t=useT(),{user,subscribe,config,reload}=useAccount(),nodes=useResource('/user/server/fetch'),notices=useResource('/user/notice/fetch'),stat=useResource('/user/getStat');const [sub,setSub]=useState(false),[notice,setNotice]=useState(null),{run}=useAction();
 // V2board 签到送流量的做法是直接把已用流量减掉，u / d 可能被减成负数
 const used=Math.max(0,(Number(subscribe?.u)||0)+(Number(subscribe?.d)||0)),total=Number(subscribe?.transfer_enable)||0,pct=total?Math.min(100,used/total*100):0;const active=subscribe?.plan_id&&(!subscribe.expired_at||subscribe.expired_at>Date.now()/1000);const remaining=Math.max(0,total-used);
 return <><Heading kicker="OVERVIEW / 01" title={t('仪表盘')} action={<span className="today">{new Intl.DateTimeFormat(undefined,{month:'long',day:'numeric',weekday:'short'}).format(new Date())}</span>}>{user.email}</Heading>
 <div className="overview-grid"><Panel className="subscription-pass"><div className="pass-head"><span>{t('我的订阅')}</span><Status tone={active?'light':'warning'}>{!subscribe?.plan_id?t('未订阅'):active?t('使用中'):t('已过期')}</Status></div><div className="pass-body"><span className="pass-caption">YOUR MEMBERSHIP</span><h2>{subscribe?.plan?.name||t('选择订阅')}</h2><p>{subscribe?.plan_id?(subscribe.expired_at?`${t('到期时间')} ${date(subscribe.expired_at)}`:t('该订阅长期有效')):t('选择最适合你的计划')}</p></div><div className="pass-bottom"><Action variant="secondary" onClick={()=>subscribe?.plan_id?setSub(true):navigate('/plan')}>{t(subscribe?.plan_id?'一键订阅':'购买订阅')}<ArrowUpRight size={16}/></Action>{subscribe?.plan_id&&<button className="text-button light" onClick={()=>navigate('/plan/'+subscribe.plan_id)}>{t('续费')} <Plus size={14}/></button>}</div><span className="pass-monogram" aria-hidden="true">h.</span></Panel>
 <Panel className="usage-card"><div className="section-title"><h2>{t('已用流量')}</h2><a href="#/traffic"><ArrowUpRight size={17}/></a></div><div className="usage-display"><strong>{bytes(used).split(' ')[0]}</strong><span>{bytes(used).split(' ')[1]} / {bytes(total)}</span></div><Progress percent={Number(pct.toFixed(1))} showInfo={false} strokeColor="#d9373f" railColor="var(--line)" size="small"/><div className="usage-meta"><span>{t('剩余流量')}<b>{bytes(remaining)}</b></span><span>{t('下次重置')}<b>{subscribe?.next_reset_at?date(subscribe.next_reset_at):subscribe?.reset_day!=null?`${subscribe.reset_day} ${t('天')}`:'—'}</b></span></div>{subscribe?.plan?.reset_price!=null&&<a className="quiet-link" href={'#/plan/'+subscribe.plan_id+'?period=reset_price'}>{t('重置已用流量')} <ArrowUpRight size={13}/></a>}</Panel>
 </div><div className="metrics-strip"><a href="#/profile"><Wallet size={19}/><span>{t('我的钱包')}<strong>{config.currency_symbol} {money(user.balance)}</strong></span><ArrowUpRight size={16}/></a><a href="#/node"><Globe size={19}/><span>{t('节点状态')}<strong>{nodes.value?.length??'—'} <small>{t('个节点')}</small></strong></span><ArrowUpRight size={16}/></a><a href="#/order"><Clock size={19}/><span>{t('待支付')}<strong>{stat.value?.[0]??'—'} <small>{t('我的订单')}</small></strong></span><ArrowUpRight size={16}/></a><CheckinTile email={user.email} onDone={()=>{reload();stat.reload()}}/></div>
 {stat.value?.[0]>0&&<Alert type="warning" showIcon title={t('还有没支付的订单')} action={<a href="#/order">{t('立即支付')}</a>}/>}<div className="dashboard-bottom"><section className="notice-section"><div className="section-title"><h2>{t('公告')}</h2><span className="mini-index">UPDATES</span></div><Load resource={notices}>{items=>items?.length?<div className="notice-feed">{items.map((n,i)=><button className="notice-row" key={n.id} onClick={()=>setNotice(n)}><span className="notice-index">{String(i+1).padStart(2,'0')}</span><div><strong>{n.title}</strong><time>{date(n.created_at)}</time></div><ArrowUpRight size={17}/></button>)}</div>:<p className="muted">{t('暂无数据')}</p>}</Load></section><div className="help-stack"><a className="help-link" href="#/knowledge"><BookOpen size={22}/><div><h3>{t('使用文档')}</h3><p>{t('学习如何使用')}</p></div><ArrowUpRight size={18}/></a><a className="help-link" href="#/ticket"><MessageSquare size={22}/><div><h3>{t('我的工单')}</h3><p>{stat.value?.[1]?`${stat.value[1]} ${t('条工单正在处理中')}`:t('遇到问题')}</p></div><ArrowUpRight size={18}/></a><TelegramChannel compact/></div></div>
 <Subscription open={sub} onClose={()=>setSub(false)}/><Modal title={notice?.title} open={!!notice} onCancel={()=>setNotice(null)} footer={null} width={740}>{notice&&<>{notice.img_url&&<img className="notice-image" src={notice.img_url} alt=""/>}<Rich content={notice.content}/></>}</Modal></>;
}
