import React,{useEffect,useState,useRef,useContext} from 'react';
import {Table,Input,Modal,Form,Select,App as AntApp,Drawer,Alert,Button as AntButton} from 'antd';
import {Plus,ArrowRight,ArrowUpRight,Search,BookOpen,Send,Globe,ArrowDownLeft} from 'lucide-react';
import {Action,Panel,Status,Heading,Load,Rich,Blank,useT,useResource,useAction,api,post,navigate,date,bytes,LocaleContext} from './core';
import {nodeOnline} from './panel';
export function Nodes(){const nodes=useResource('/user/server/fetch'),t=useT(),[search,setSearch]=useState('');return <><Heading kicker="NETWORK / 04" title={t('节点状态')} action={<Input prefix={<Search size={16}/>} aria-label={t('搜索')} placeholder={t('搜索')} value={search} onChange={e=>setSearch(e.target.value)}/>}/><Load resource={nodes}>{list=><div className="node-grid">{(list||[]).filter(n=>n.name.toLowerCase().includes(search.toLowerCase())).map(n=>{const online=nodeOnline(n);return <Panel key={n.type+'-'+n.id}><div className="node-head"><div className="node-globe"><Globe size={24}/></div><Status tone={online?'success':'default'}>{t(online?'在线':'离线')}</Status></div><h2>{n.name}</h2><div className="node-meta"><span>{n.type}</span><b>× {n.rate}</b></div><div className="tag-row">{(n.tags||[]).map(tag=><Status key={tag}>{tag}</Status>)}</div></Panel>})}</div>}</Load></>}
export function Traffic(){const t=useT(),traffic=useResource('/user/stat/getTrafficLog');return <><Heading kicker="USAGE / 04" title={t('流量明细')}>{t('流量明细仅保留近月数据以供查询。')}</Heading><Load resource={traffic}>{list=><Table rowKey={(r,i)=>r.id||r.record_at+'-'+i} dataSource={list||[]} scroll={{x:600}} pagination={{pageSize:15,hideOnSinglePage:true}} columns={[{title:t('记录时间'),dataIndex:'record_at',render:d=>date(d)},{title:t('实际上行'),dataIndex:'u',render:(v,r)=>bytes(v/(Number(r.server_rate)||1))},{title:t('实际下行'),dataIndex:'d',render:(v,r)=>bytes(v/(Number(r.server_rate)||1))},{title:t('扣费倍率'),dataIndex:'server_rate',render:r=>r+' ×'},{title:t('总计'),render:(_,r)=>bytes(Number(r.u)+Number(r.d))}]}/>}</Load></>}
export function Knowledge(){const {locale}=useContext(LocaleContext),t=useT(),[search,setSearch]=useState(''),[keyword,setKeyword]=useState(''),knowledge=useResource('/user/knowledge/fetch',{keyword,language:locale}),[article,setArticle]=useState(null),[loading,setLoading]=useState(false),{run}=useAction();const open=id=>run(async()=>{setLoading(true);try{setArticle(await api('/user/knowledge/fetch',{id,language:locale}))}finally{setLoading(false)}});
 useEffect(()=>{const clicked=e=>{const item=e.target.closest('[data-knowledge-id]');if(item)open(item.dataset.knowledgeId)};document.addEventListener('click',clicked);return()=>document.removeEventListener('click',clicked)},[]);
 return <><Heading kicker="GUIDE / 07" title={t('使用文档')}/><div className="knowledge-search"><Search size={24}/><Input variant="borderless" aria-label={t('搜索文档')} placeholder={t('搜索文档')} value={search} onChange={e=>setSearch(e.target.value)} onPressEnter={()=>setKeyword(search)}/><Action onClick={()=>setKeyword(search)}>{t('搜索')}</Action></div><Load resource={knowledge}>{groups=>Object.keys(groups||{}).length?<div className="knowledge-grid">{Object.entries(groups||{}).map(([category,list])=><section key={category}><div className="section-title"><h2>{category}</h2><span>{list.length}</span></div>{list.map(item=><button className="article-link" key={item.id} onClick={()=>open(item.id)}><BookOpen size={19}/><div><strong>{item.title}</strong><time>{date(item.updated_at)}</time></div><ArrowUpRight size={16}/></button>)}</section>)}</div>:<Blank/>}</Load><Drawer title={article?.title||t('使用文档')} open={!!article||loading} onClose={()=>setArticle(null)} size="large" loading={loading}><Rich rich content={article?.body||article?.content}/></Drawer></>}
export function Tickets({id}){
 const t=useT(),tickets=useResource('/user/ticket/fetch'),detail=useResource(id?'/user/ticket/fetch':null,{id}),[create,setCreate]=useState(false),[reply,setReply]=useState(''),[form]=Form.useForm(),{busy,run}=useAction(),{modal}=AntApp.useApp(),messages=useRef();
 useEffect(()=>{if(!id)return;const timer=setInterval(()=>detail.reload(),6000);return()=>clearInterval(timer)},[id]);
 useEffect(()=>{if(messages.current)messages.current.scrollTop=messages.current.scrollHeight},[detail.value?.message?.length,id]);
 const submit=v=>run(async()=>{await post('/user/ticket/save',v);setCreate(false);form.resetFields();tickets.reload()},t('创建成功'));
 const send=()=>run(async()=>{await post('/user/ticket/reply',{id,message:reply.trim()});setReply('');detail.reload()},t('回复成功'));
 const close=()=>modal.confirm({title:t('关闭工单'),okText:t('关闭'),cancelText:t('取消'),onOk:()=>run(async()=>{await post('/user/ticket/close',{id});detail.reload();tickets.reload()},t('关闭成功'))});
 return <><Heading kicker="SUPPORT / 08" title={t('我的工单')} action={<Action onClick={()=>setCreate(true)}><Plus size={17}/>{t('新的工单')}</Action>}/><div className="ticket-workspace"><aside className="ticket-list"><Load resource={tickets}>{list=>list?.length?list.map(item=><button key={item.id} className={'ticket-preview '+(String(item.id)===String(id)?'active':'')} onClick={()=>navigate('/ticket/'+item.id)}><div><span>#{item.id}</span><Status tone={item.status?'default':'warning'}>{t(item.status?'已关闭':item.reply_status?'待回复':'处理中')}</Status></div><strong>{item.subject}</strong><time>{date(item.updated_at||item.created_at)}</time></button>):<Blank/>}</Load></aside><section className="ticket-conversation">{id?<Load resource={detail}>{item=>item&&<><header><div><h2>{item.subject}</h2><span>#{item.id} · {t(['低','中','高'][item.level])}</span></div>{item.status===0&&<AntButton onClick={close}>{t('关闭')}</AntButton>}</header><div className="messages" ref={messages}>{(item.message||[]).map((m,i)=><div key={m.id||i} className={'message '+(m.is_me?'mine':'theirs')}><div>{m.message}</div><time>{date(m.created_at,true)}</time></div>)}</div>{item.status===0?<div className="reply-composer"><Input.TextArea value={reply} onChange={e=>setReply(e.target.value)} aria-label={t('输入内容回复工单')} placeholder={t('输入内容回复工单')} autoSize={{minRows:2,maxRows:5}}/><Action isIconOnly aria-label={t('回复')} loading={busy} disabled={!reply.trim()} onClick={send}><Send size={18}/></Action></div>:<div className="closed-ticket">{t('已关闭')}</div>}</>}</Load>:<div className="ticket-welcome"><span className="support-glyph">?</span><h2>{t('遇到问题')}</h2><p>{t('遇到问题可以通过工单与我们沟通')}</p><Action variant="secondary" onClick={()=>setCreate(true)}>{t('新的工单')}</Action></div>}</section></div><Modal title={t('新的工单')} open={create} onCancel={()=>setCreate(false)} footer={null} destroyOnHidden><Form form={form} layout="vertical" onFinish={submit} initialValues={{level:1}}><Form.Item name="subject" label={t('主题')} rules={[{required:true,whitespace:true}]}><Input aria-label={t('主题')} maxLength={200}/></Form.Item><Form.Item name="level" label={t('工单级别')} rules={[{required:true}]}><Select aria-label={t('工单级别')} options={['低','中','高'].map((v,i)=>({value:i,label:t(v)}))}/></Form.Item><Form.Item name="message" label={t('消息')} rules={[{required:true,whitespace:true}]}><Input.TextArea aria-label={t('消息')} rows={5}/></Form.Item><Action type="submit" fullWidth loading={busy}>{t('确认')}</Action></Form></Modal></>;
}
